# Generated by Django 2.1.3 on 2019-03-13 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id_card', models.CharField(default=None, max_length=200, primary_key=True, serialize=False, verbose_name='id_card')),
                ('user_name', models.CharField(default=None, max_length=200, verbose_name='user_name')),
                ('phone_number', models.IntegerField(default=None, verbose_name='phone_number')),
                ('regist_times', models.DateTimeField(default=datetime.datetime(2019, 3, 13, 9, 53, 20, 409051), verbose_name='regist_times')),
            ],
        ),
    ]
